// vue-mybooks/src/components/carousel/BookCarousel.vue
<template>
  <div class="carousel-container">
    <button class="arrow" @click="prev" :disabled="startIndex === 0">&#8592;</button>
    <div class="carousel" :class="{ highlight: isHighlighted }">
      <div class="books-container">
        <BookCard
          v-for="(book, idx) in visibleBooks"
          :key="book.key || idx"
          :title="book.title || 'Sin título'"
          :cover-id="book.cover_i"
          @click="handleClick(book)"
          class="book-item"
        />
        <div v-if="books.length === 0" class="empty-message">
          No hay libros en esta lista todavía
        </div>
      </div>
    </div>
    <button class="arrow" @click="next" :disabled="startIndex + visibleCount >= books.length">&#8594;</button>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import BookCard from './BookCard.vue'
import { useBookStore } from '../../stores/bookStore'

const props = defineProps({
  books: {
    type: Array,
    required: true,
    default: () => []
  }
})
const emit = defineEmits(['book-click'])

const bookStore = useBookStore()
const visibleCount = 3
const startIndex = ref(0)
const isHighlighted = ref(false)

// Observar cambios en la lista de libros
watch(() => props.books, () => {
  // Resetear al principio cuando cambia la lista
  startIndex.value = 0
  highlightCarousel()
}, { deep: true })

// Observar cambios en el store para resaltar el carrusel
watch(() => bookStore.currentBooks, () => {
  highlightCarousel()
}, { deep: true })

const visibleBooks = computed(() =>
  props.books.slice(startIndex.value, startIndex.value + visibleCount)
)

function prev() {
  if (startIndex.value > 0) startIndex.value--
}

function next() {
  if (startIndex.value + visibleCount < props.books.length) startIndex.value++
}

function handleClick(book) {
  emit('book-click', book)
}

function highlightCarousel() {
  isHighlighted.value = true
  setTimeout(() => {
    isHighlighted.value = false
  }, 1000)
}
</script>

<style scoped>
.carousel-container {
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 2em auto;
  max-width: 900px;
  padding: 1em 0;
}

.carousel {
  width: 420px; /* Ancho fijo para 3 libros */
  overflow: hidden;
  background: #f8f8f8;
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  padding: 1.5em 1em;
  margin: 0 1em;
  transition: box-shadow 0.5s, transform 0.5s;
}

.carousel.highlight {
  box-shadow: 0 0 20px rgba(248, 204, 204, 0.8);
  transform: scale(1.02);
}

.books-container {
  display: flex;
  justify-content: center;
  gap: 1em;
}

.book-item {
  cursor: pointer;
  transition: transform 0.2s;
}

.book-item:hover {
  transform: translateY(-5px);
}

.arrow {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  border: 2px solid #ccc;
  background: #fff;
  font-size: 1.2em;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.2s;
}

.arrow:hover:not(:disabled) {
  background: #f8cccc;
  border-color: #f8cccc;
  color: #a33;
}

.arrow:disabled {
  opacity: 0.3;
  cursor: not-allowed;
}

.empty-message {
  font-size: 1.1em;
  color: #888;
  text-align: center;
  padding: 2em 0;
}
</style>

// svelte-mybooks/src/lib/components/BookCarousel.svelte
<script lang="ts">
  import { fade } from 'svelte/transition';
  import { createEventDispatcher } from 'svelte';
  
  export let books: Array<{
    title: string;
    author_name?: string[];
    cover_i?: number;
    first_publish_year?: number;
    key: string;
  }> = [];
  
  export let title: string = '';
  
  const dispatch = createEventDispatcher();
  
  let currentIndex = 0;
  const booksPerPage = 3;
  
  $: totalPages = Math.ceil(books.length / booksPerPage);
  $: visibleBooks = books.slice(currentIndex * booksPerPage, (currentIndex + 1) * booksPerPage);
  
  function handleBookClick(book: typeof books[0]) {
    dispatch('bookClick', book);
  }
  
  function nextPage() {
    if (currentIndex < totalPages - 1) {
      currentIndex++;
    }
  }
  
  function prevPage() {
    if (currentIndex > 0) {
      currentIndex--;
    }
  }

  function handleImageError(event: Event) {
    const img = event.target as HTMLImageElement;
    img.src = 'https://via.placeholder.com/150x200?text=No+Image';
  }
</script>

<div class="carousel-container">
  {#if title}
    <h2 class="carousel-title">{title}</h2>
  {/if}
  
  <div class="carousel">
    <button 
      class="nav-button prev" 
      on:click={prevPage}
      disabled={currentIndex === 0}
      aria-label="Página anterior"
    >
      ←
    </button>
    
    <div class="books-container">
      {#each visibleBooks as book (book.key)}
        <button 
          type="button"
          class="book-card" 
          on:click={() => handleBookClick(book)}
          transition:fade
        >
          <div class="book-cover">
            {#if book.cover_i}
              <img 
                src={`https://covers.openlibrary.org/b/id/${book.cover_i}-M.jpg`} 
                alt={`Portada de ${book.title}`}
                on:error={handleImageError}
              />
            {:else}
              <div class="no-cover">Sin portada</div>
            {/if}
          </div>
          <div class="book-info">
            <h3 class="book-title">{book.title}</h3>
            {#if book.author_name}
              <p class="book-author">{book.author_name[0]}</p>
            {/if}
            {#if book.first_publish_year}
              <p class="book-year">{book.first_publish_year}</p>
            {/if}
          </div>
        </button>
      {/each}
    </div>
    
    <button 
      class="nav-button next" 
      on:click={nextPage}
      disabled={currentIndex >= totalPages - 1}
      aria-label="Página siguiente"
    >
      →
    </button>
  </div>
  
  {#if totalPages > 1}
    <div class="carousel-dots">
      {#each Array(totalPages) as _, i}
        <button 
          class="dot" 
          class:active={i === currentIndex}
          on:click={() => currentIndex = i}
          aria-label={`Ir a página ${i + 1}`}
        ></button>
      {/each}
    </div>
  {/if}
</div>

<style>
  .carousel-container {
    width: 100%;
    max-width: 1200px;
    margin: 2rem auto;
    padding: 0 1rem;
    position: relative;
  }

  .carousel-title {
    font-size: 1.75rem;
    color: #5c4033;
    margin-bottom: 2rem;
    font-weight: 600;
    position: relative;
    padding-bottom: 0.75rem;
  }

  .carousel-title::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 60px;
    height: 3px;
    background: #5c4033;
    border-radius: 2px;
  }

  .carousel {
    display: flex;
    align-items: center;
    gap: 1.5rem;
    position: relative;
    padding: 1rem 0;
  }

  .books-container {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 2.5rem;
    flex: 1;
    overflow: hidden;
    padding: 0.5rem;
  }

  .nav-button {
    background: #5c4033;
    color: white;
    border: none;
    width: 48px;
    height: 48px;
    border-radius: 50%;
    font-size: 1.4rem;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.3s ease;
    box-shadow: 0 2px 8px rgba(92, 64, 51, 0.2);
    z-index: 2;
  }

  .nav-button:hover:not(:disabled) {
    background: #4a3329;
    transform: scale(1.05);
    box-shadow: 0 4px 12px rgba(92, 64, 51, 0.3);
  }

  .nav-button:disabled {
    background: #e0e0e0;
    cursor: not-allowed;
    box-shadow: none;
  }

  .book-card {
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
    overflow: hidden;
    transition: all 0.3s ease;
    border: 1px solid rgba(92, 64, 51, 0.1);
    cursor: pointer;
    padding: 0;
    text-align: left;
    width: 100%;
  }

  .book-card:hover {
    transform: translateY(-8px);
    box-shadow: 0 8px 24px rgba(92, 64, 51, 0.15);
    border-color: rgba(92, 64, 51, 0.2);
  }

  .book-cover {
    width: 100%;
    height: 320px;
    background: #f5f0e6;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    position: relative;
  }

  .book-cover::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 60px;
    background: linear-gradient(to top, rgba(0,0,0,0.1), transparent);
    pointer-events: none;
  }

  .book-cover img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform 0.3s ease;
  }

  .book-card:hover .book-cover img {
    transform: scale(1.05);
  }

  .no-cover {
    color: #5c4033;
    font-size: 1rem;
    text-align: center;
    padding: 1.5rem;
    background: #f5f0e6;
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .book-info {
    padding: 1.25rem;
    background: white;
  }

  .book-title {
    font-size: 1.1rem;
    font-weight: 600;
    color: #5c4033;
    margin: 0 0 0.75rem 0;
    line-height: 1.4;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  .book-author {
    font-size: 0.95rem;
    color: #5c4033;
    opacity: 0.85;
    margin: 0 0 0.5rem 0;
    font-weight: 500;
  }

  .book-year {
    font-size: 0.85rem;
    color: #5c4033;
    opacity: 0.7;
    margin: 0;
    font-weight: 500;
  }

  .carousel-dots {
    display: flex;
    justify-content: center;
    gap: 0.75rem;
    margin-top: 2rem;
  }

  .dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background: #e0e0e0;
    border: none;
    padding: 0;
    cursor: pointer;
    transition: all 0.3s ease;
  }

  .dot:hover {
    background: #c0c0c0;
  }

  .dot.active {
    background: #5c4033;
    transform: scale(1.2);
    box-shadow: 0 2px 4px rgba(92, 64, 51, 0.2);
  }

  @media (max-width: 1024px) {
    .books-container {
      gap: 2rem;
    }

    .book-cover {
      height: 280px;
    }
  }

  @media (max-width: 768px) {
    .carousel-title {
      font-size: 1.5rem;
      margin-bottom: 1.5rem;
    }

    .books-container {
      grid-template-columns: repeat(1, 1fr);
      gap: 1.5rem;
    }

    .book-cover {
      height: 240px;
    }

    .nav-button {
      width: 40px;
      height: 40px;
      font-size: 1.2rem;
    }

    .book-info {
      padding: 1rem;
    }

    .book-title {
      font-size: 1rem;
    }
  }
</style>
