// svelte-mybooks/src/lib/components/RatingModal.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { fade, slide } from 'svelte/transition';

  export let isOpen = false;
  export let bookKey = '';

  const dispatch = createEventDispatcher<{
    save: { rating: number };
    close: void;
  }>();

  let rating = 0;
  let hoverRating = 0;

  // Reset rating when modal opens for a new book
  $: if (isOpen) {
    rating = 0;
    hoverRating = 0;
  }

  function handleStarClick(value: number) {
    rating = value;
  }

  function handleStarHover(value: number) {
    hoverRating = value;
  }

  function handleStarLeave() {
    hoverRating = 0;
  }

  function handleSave() {
    if (rating > 0) {
      dispatch('save', { rating });
      closeModal();
    }
  }

  function closeModal() {
    dispatch('close');
  }

  function handleBackdropClick(event: MouseEvent | KeyboardEvent) {
    if (event.target === event.currentTarget) {
      closeModal();
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      closeModal();
    }
  }
</script>

<svelte:window on:keydown={handleKeydown} />

{#if isOpen}
  <div 
    class="modal-backdrop" 
    on:click={handleBackdropClick}
    on:keydown={(e) => e.key === 'Enter' && handleBackdropClick(e)}
    role="button"
    tabindex="0"
    transition:fade={{ duration: 200 }}
  >
    <div class="modal-content" transition:slide={{ duration: 200 }}>
      <button class="close-button" on:click={closeModal}>×</button>
      
      <div class="modal-body">
        <h2 class="modal-title">Califica este libro</h2>
        
        <div class="stars-container">
          {#each Array(5) as _, i}
            <button
              class="star-button"
              on:click={() => handleStarClick(i + 1)}
              on:mouseenter={() => handleStarHover(i + 1)}
              on:mouseleave={handleStarLeave}
              aria-label={`${i + 1} estrellas`}
            >
              <span class="star {((hoverRating || rating) > i) ? 'filled' : ''}">
                ★
              </span>
            </button>
          {/each}
        </div>

        <div class="rating-text">
          {#if rating > 0}
            {rating} {rating === 1 ? 'estrella' : 'estrellas'}
          {:else}
            Selecciona una calificación
          {/if}
        </div>

        <button 
          class="save-button" 
          on:click={handleSave}
          disabled={rating === 0}
        >
          Guardar calificación
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .modal-backdrop {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 1100;
    padding: 1rem;
  }

  .modal-content {
    background: white;
    border-radius: 12px;
    width: 100%;
    max-width: 400px;
    position: relative;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  }

  .close-button {
    position: absolute;
    top: 1rem;
    right: 1rem;
    background: none;
    border: none;
    font-size: 1.5rem;
    color: #5c4033;
    cursor: pointer;
    width: 2rem;
    height: 2rem;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    transition: background-color 0.3s ease;
  }

  .close-button:hover {
    background-color: #f5f0e6;
  }

  .modal-body {
    padding: 2rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1.5rem;
  }

  .modal-title {
    font-size: 1.5rem;
    font-weight: 600;
    color: #5c4033;
    margin: 0;
    text-align: center;
  }

  .stars-container {
    display: flex;
    gap: 0.5rem;
  }

  .star-button {
    background: none;
    border: none;
    padding: 0;
    cursor: pointer;
    font-size: 2rem;
    color: #ddd;
    transition: transform 0.2s ease;
  }

  .star-button:hover {
    transform: scale(1.1);
  }

  .star {
    display: inline-block;
  }

  .star.filled {
    color: #ffd700;
  }

  .rating-text {
    color: #5c4033;
    font-size: 1.1rem;
    text-align: center;
    min-height: 1.5rem;
  }

  .save-button {
    padding: 0.75rem 1.5rem;
    background: #5c4033;
    color: white;
    border: none;
    border-radius: 0.5rem;
    font-family: 'Poppins', sans-serif;
    font-size: 1rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.3s ease;
    width: 100%;
  }

  .save-button:hover:not(:disabled) {
    background: #4a3329;
  }

  .save-button:disabled {
    background: #ccc;
    cursor: not-allowed;
  }
</style>

// vue-mybooks/src/components/search/RatingModal.vue
<template>
  <div v-if="isOpen" class="rating-modal-backdrop" @click.self="closeWithoutRating">
    <div class="rating-modal">
      <h3>¿Qué te pareció este libro?</h3>
      <img v-if="book.cover_i" :src="`https://covers.openlibrary.org/b/id/${book.cover_i}-L.jpg`" alt="Portada" class="cover" />
      <p class="book-title">{{ book.title }}</p>
      
      <div class="star-rating">
        <span 
          v-for="star in 5" 
          :key="star" 
          class="star" 
          :class="{ 'filled': star <= currentRating, 'hovered': star <= hoverRating }"
          @click="setRating(star)"
          @mouseenter="hoverRating = star"
          @mouseleave="hoverRating = 0"
        >
          ★
        </span>
      </div>
      <div class="rating-text">{{ getRatingText(currentRating) }}</div>
      
      <div class="buttons">
        <button class="skip-btn" @click="closeWithoutRating">Valorar después</button>
        <button class="submit-btn" @click="submitRating" :disabled="currentRating === 0">Guardar</button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, defineProps, defineEmits } from 'vue'

const props = defineProps({
  book: Object,
  isOpen: Boolean
})

const emit = defineEmits(['close', 'rate'])

const currentRating = ref(0)
const hoverRating = ref(0)

function getRatingText(rating) {
  switch(rating) {
    case 0: return 'Selecciona tu valoración';
    case 1: return 'No me gustó';
    case 2: return 'Está bien';
    case 3: return 'Me gustó';
    case 4: return 'Me gustó mucho';
    case 5: return 'Excelente';
    default: return '';
  }
}

function setRating(rating) {
  currentRating.value = rating
}

function submitRating() {
  emit('rate', { bookKey: props.book.key, rating: currentRating.value })
  emit('close')
}

function closeWithoutRating() {
  emit('close')
}
</script>

<style scoped>
.rating-modal-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.8);
  backdrop-filter: blur(5px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1100;
  animation: fadeIn 0.3s;
}

.rating-modal {
  background: white;
  padding: 2em;
  border-radius: 12px;
  width: 90%;
  max-width: 400px;
  display: flex;
  flex-direction: column;
  align-items: center;
  box-shadow: 0 4px 20px rgba(0,0,0,0.2);
}

.cover {
  width: 100px;
  height: 150px;
  object-fit: cover;
  border-radius: 8px;
  margin: 1em 0;
  box-shadow: 0 4px 8px rgba(0,0,0,0.1);
}

.book-title {
  font-weight: bold;
  margin-bottom: 1em;
  font-size: 1.1em;
}

.star-rating {
  display: flex;
  gap: 0.5em;
  margin: 1em 0;
}

.star {
  font-size: 2.5em;
  cursor: pointer;
  color: #ddd;
  transition: all 0.2s;
}

.star.filled {
  color: #ffcc00;
}

.star.hovered {
  color: #ffdd55;
  transform: scale(1.1);
}

.rating-text {
  height: 1.5em;
  margin-bottom: 1.5em;
  font-style: italic;
  color: #666;
}

.buttons {
  display: flex;
  gap: 1em;
  margin-top: 1em;
}

.skip-btn, .submit-btn {
  padding: 0.7em 1.5em;
  border-radius: 8px;
  border: none;
  font-size: 1em;
  cursor: pointer;
  transition: all 0.2s;
}

.skip-btn {
  background: #eee;
  color: #666;
}

.skip-btn:hover {
  background: #ddd;
}

.submit-btn {
  background: #f8cccc;
  color: #a33;
}

.submit-btn:hover:not(:disabled) {
  background: #f6bbbb;
  transform: translateY(-2px);
}

.submit-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}
</style>
